[project]
name = "eth-analyzer"
version = "0.1.0"
description = ""
authors = [
    {name = "klianchenkov.va",email = "klianchenkov.va@dozen.mephi.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv (>=1.2.2,<2.0.0)",
    "web3 (>=7.16.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)"
]

[tool.poetry.dependencies]
python = ">=3.12,<4"

[tool.poetry]
packages = [{include = "eth_analyzer", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
start = "eth_analyzer.async_parser:main"